version: "3.9"
services:
  iac:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
