version: "3.9"
services:
  iac:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - 8090:8090
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
