version: "3.9"

services:
  iac:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - 8090:8090
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
